version: '3.8'
services:
    map-link-dev:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: map-link-dev
      restart: always
      env_file:
        - .env
      ports:
        - '${APP_PORT}:${APP_PORT}'

